// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLPOadXLp-TBMhvnVBOnVpMLStPyRgVk0',
    appId: '1:158960183601:web:f8c67f812dcb3b1a87e810',
    messagingSenderId: '158960183601',
    projectId: 'euromilions-b145a',
    authDomain: 'euromilions-b145a.firebaseapp.com',
    storageBucket: 'euromilions-b145a.appspot.com',
    measurementId: 'G-TEQ8VQD6Q3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf6q2-gQyExkB5saoQLlV4TYhIPpwZoL4',
    appId: '1:158960183601:android:4ab46d9746a6da8b87e810',
    messagingSenderId: '158960183601',
    projectId: 'euromilions-b145a',
    storageBucket: 'euromilions-b145a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR9ZGYdz36Z0Y5gTYrDrRKCESXuPubvsU',
    appId: '1:158960183601:ios:20a4b2262a16169387e810',
    messagingSenderId: '158960183601',
    projectId: 'euromilions-b145a',
    storageBucket: 'euromilions-b145a.appspot.com',
    iosBundleId: 'com.example.euromilions',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR9ZGYdz36Z0Y5gTYrDrRKCESXuPubvsU',
    appId: '1:158960183601:ios:20a4b2262a16169387e810',
    messagingSenderId: '158960183601',
    projectId: 'euromilions-b145a',
    storageBucket: 'euromilions-b145a.appspot.com',
    iosBundleId: 'com.example.euromilions',
  );
}
